name: Record and update Benchmark animations
on:
  workflow_dispatch:
# Uncomment to run every midnight
#  schedule:
#    - cron:  '0 0 * * *'
jobs:
  record:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Record and update Benchmark animations
        uses: cyberbotics/benchmark-record-action@forkSystem 
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BOT_PAT_KEY: ${{ secrets.BOT_PAT_KEY }}
          BOT_USERNAME: ${{ secrets.BOT_USERNAME }}
